stages:
  - export
  - build

variables:
  UNITY_COMMAND: "xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity -batchmode -nographics -logfile /dev/stdout -quit"
  EXPORT_PACKAGE_PATH: 'Builds/HTCPackagesBootstrapper.unitypackage'

.unity_activate: &unity_activate |-
  echo ${UNITY_LICENSE_2019_3_0} > /unity-license.ulf
  eval ${UNITY_COMMAND} -username "${UNITY_EMAIL}" -password "${UNITY_PASSWORD}" -manualLicenseFile /unity-license.ulf
  eval ${UNITY_COMMAND} -username "${UNITY_EMAIL}" -password "${UNITY_PASSWORD}"

.unity_return_license: &unity_return_license |-
  eval ${UNITY_COMMAND} -returnLicense

.unity_job_template: &unity_job_template
  image: gableroux/unity3d:${IMAGE_TAG}
  only:
    - master
    - merge_requests

  script:
    - *unity_activate
    - echo 'hi'
    - *unity_return_license

export:unitypackage:
  <<: *unity_job_template
  stage: export
  variables:
    IMAGE_TAG: '2019.3.7f1-windows'

build:windows-2019.1:
  <<: *unity_job_template
  stage: build
  variables:
    IMAGE_TAG: '2019.1.13f1-windows'

build:windows-2019.2:
  <<: *unity_job_template
  stage: build
  variables:
    IMAGE_TAG: '2019.2.20f1-windows'

build:windows-2019.3:
  <<: *unity_job_template
  stage: build
  variables:
    IMAGE_TAG: '2019.3.7f1-windows'
